import { Deck } from "./interfaces"
import { ObjectId } from "mongodb"
export let starterDeck: Deck = {
    _id: new ObjectId(),
    userId: new ObjectId(),
    deckName: "- Green-White Starter Deck -",
    cards: [
        {
            _id: new ObjectId(),
            id: "45260a6a-bb6a-521c-98c3-cd6643ac4f46",
            name: "Plains",
            manaCost: "",
            cmc: 0,
            colorIdentity: ["W"],
            multiverseid: 495098,
            types: ["Land"],
            imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=495098&type=card",
            rarity: "Common"
        },
        {
            _id: new ObjectId(),
            id: "45260a6a-bb6a-521c-98c3-cd6643ac4f46",
            name: "Plains",
            manaCost: "",
            cmc: 0,
            colorIdentity: ["W"],
            multiverseid: 495098,
            types: ["Land"],
            imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=495098&type=card",
            rarity: "Common"
        },
        {
            _id: new ObjectId(),
            id: "45260a6a-bb6a-521c-98c3-cd6643ac4f46",
            name: "Plains",
            manaCost: "",
            cmc: 0,
            colorIdentity: ["W"],
            multiverseid: 495098,
            types: ["Land"],
            imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=495098&type=card",
            rarity: "Common"
        },
        {
            _id: new ObjectId(),
            id: "45260a6a-bb6a-521c-98c3-cd6643ac4f46",
            name: "Plains",
            manaCost: "",
            cmc: 0,
            colorIdentity: ["W"],
            multiverseid: 495098,
            types: ["Land"],
            imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=495098&type=card",
            rarity: "Common"
        },
        {
            _id: new ObjectId(),
            id: "45260a6a-bb6a-521c-98c3-cd6643ac4f46",
            name: "Plains",
            manaCost: "",
            cmc: 0,
            colorIdentity: ["W"],
            multiverseid: 495098,
            types: ["Land"],
            imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=495098&type=card",
            rarity: "Common"
        },
        {
            _id: new ObjectId(),
            id: "45260a6a-bb6a-521c-98c3-cd6643ac4f46",
            name: "Plains",
            manaCost: "",
            cmc: 0,
            colorIdentity: ["W"],
            multiverseid: 495098,
            types: ["Land"],
            imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=495098&type=card",
            rarity: "Common"
        },
        {
            _id: new ObjectId(),
            id: "45260a6a-bb6a-521c-98c3-cd6643ac4f46",
            name: "Plains",
            manaCost: "",
            cmc: 0,
            colorIdentity: ["W"],
            multiverseid: 495098,
            types: ["Land"],
            imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=495098&type=card",
            rarity: "Common"
        },
        {
            _id: new ObjectId(),
            id: "45260a6a-bb6a-521c-98c3-cd6643ac4f46",
            name: "Plains",
            manaCost: "",
            cmc: 0,
            colorIdentity: ["W"],
            multiverseid: 495098,
            types: ["Land"],
            imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=495098&type=card",
            rarity: "Common"
        },
        {
            _id: new ObjectId(),
            id: "45260a6a-bb6a-521c-98c3-cd6643ac4f46",
            name: "Plains",
            manaCost: "",
            cmc: 0,
            colorIdentity: ["W"],
            multiverseid: 495098,
            types: ["Land"],
            imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=495098&type=card",
            rarity: "Common"
        },
        {
            _id: new ObjectId(),
            id: "45260a6a-bb6a-521c-98c3-cd6643ac4f46",
            name: "Plains",
            manaCost: "",
            cmc: 0,
            colorIdentity: ["W"],
            multiverseid: 495098,
            types: ["Land"],
            imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=495098&type=card",
            rarity: "Common"
        },
        {
            _id: new ObjectId(),
            id: "2f8a3f3d-3b11-5f26-b766-0b0bbda0a5bb",
            name: "Forest",
            manaCost: "",
            cmc: 0,
            colorIdentity: ["G"],
            multiverseid: 495102,
            types: ["Land"],
            imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=495102&type=card",
            rarity: "Common"
        },
        {
            _id: new ObjectId(),
            id: "2f8a3f3d-3b11-5f26-b766-0b0bbda0a5bb",
            name: "Forest",
            manaCost: "",
            cmc: 0,
            colorIdentity: ["G"],
            multiverseid: 495102,
            types: ["Land"],
            imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=495102&type=card",
            rarity: "Common"
        },
        {
            _id: new ObjectId(),
            id: "2f8a3f3d-3b11-5f26-b766-0b0bbda0a5bb",
            name: "Forest",
            manaCost: "",
            cmc: 0,
            colorIdentity: ["G"],
            multiverseid: 495102,
            types: ["Land"],
            imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=495102&type=card",
            rarity: "Common"
        },
        {
            _id: new ObjectId(),
            id: "2f8a3f3d-3b11-5f26-b766-0b0bbda0a5bb",
            name: "Forest",
            manaCost: "",
            cmc: 0,
            colorIdentity: ["G"],
            multiverseid: 495102,
            types: ["Land"],
            imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=495102&type=card",
            rarity: "Common"
        }, {
            _id: new ObjectId(),
            id: "2f8a3f3d-3b11-5f26-b766-0b0bbda0a5bb",
            name: "Forest",
            manaCost: "",
            cmc: 0,
            colorIdentity: ["G"],
            multiverseid: 495102,
            types: ["Land"],
            imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=495102&type=card",
            rarity: "Common"
        },
        {
            _id: new ObjectId(),
            id: "2f8a3f3d-3b11-5f26-b766-0b0bbda0a5bb",
            name: "Forest",
            manaCost: "",
            cmc: 0,
            colorIdentity: ["G"],
            multiverseid: 495102,
            types: ["Land"],
            imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=495102&type=card",
            rarity: "Common"
        },
        {
            _id: new ObjectId(),
            id: "2f8a3f3d-3b11-5f26-b766-0b0bbda0a5bb",
            name: "Forest",
            manaCost: "",
            cmc: 0,
            colorIdentity: ["G"],
            multiverseid: 495102,
            types: ["Land"],
            imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=495102&type=card",
            rarity: "Common"
        },
        {
            _id: new ObjectId(),
            id: "2f8a3f3d-3b11-5f26-b766-0b0bbda0a5bb",
            name: "Forest",
            manaCost: "",
            cmc: 0,
            colorIdentity: ["G"],
            multiverseid: 495102,
            types: ["Land"],
            imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=495102&type=card",
            rarity: "Common"
        },
        {
            _id: new ObjectId(),
            id: "2f8a3f3d-3b11-5f26-b766-0b0bbda0a5bb",
            name: "Forest",
            manaCost: "",
            cmc: 0,
            colorIdentity: ["G"],
            multiverseid: 495102,
            types: ["Land"],
            imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=495102&type=card",
            rarity: "Common"
        },
        {
            _id: new ObjectId(),
            id: "f51da6ba-01ef-51a9-9857-d2aa83642d48",
            name: "Selesnya Guildgate",
            manaCost: "",
            cmc: 0,
            colorIdentity: ["G", "W"],
            multiverseid: 496077,
            types: ["Land"],
            imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=496077&type=card",
            rarity: "Common"
        },
        {
            _id: new ObjectId(),
            id: "f51da6ba-01ef-51a9-9857-d2aa83642d48",
            name: "Selesnya Guildgate",
            manaCost: "",
            cmc: 0,
            colorIdentity: ["G", "W"],
            multiverseid: 496077,
            types: ["Land"],
            imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=496077&type=card",
            rarity: "Common"
        },
        {
            _id: new ObjectId(),
            id: "f51da6ba-01ef-51a9-9857-d2aa83642d48",
            name: "Selesnya Guildgate",
            manaCost: "",
            cmc: 0,
            colorIdentity: ["G", "W"],
            multiverseid: 496077,
            types: ["Land"],
            imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=496077&type=card",
            rarity: "Common"
        },
        {
            _id: new ObjectId(),
            id: "f51da6ba-01ef-51a9-9857-d2aa83642d48",
            name: "Selesnya Guildgate",
            manaCost: "",
            cmc: 0,
            colorIdentity: ["G", "W"],
            multiverseid: 496077,
            types: ["Land"],
            imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=496077&type=card",
            rarity: "Common"
        },
        {
            _id: new ObjectId(),
            id: "9c74e719-0d75-56a3-8afc-1c2d542fb99c",
            name: "Llanowar Elves",
            manaCost: "{G}",
            cmc: 1,
            colorIdentity: ["G"],
            multiverseid: 450261,
            types: ["Creature"],
            imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=450261&type=card",
            rarity: "Common"
        },
        {
            _id: new ObjectId(),
            id: "e87f90e1-1453-5c4d-9196-adddaf575760",
            name: "Elvish Mystic",
            manaCost: "{G}",
            cmc: 1,
            colorIdentity: ["G"],
            multiverseid: 512326,
            types: ["Creature"],
            imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=512326&type=card",
            rarity: "Special"
        },
        {
            _id: new ObjectId(),
            id: "912101c7-cb9f-59df-8761-7eccdbb05c13",
            name: "Healer's Hawk",
            manaCost: "{W}",
            cmc: 1,
            colorIdentity: ["W"],
            multiverseid: 489591,
            types: ["Creature"],
            imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=489591&type=card",
            rarity: "Common"
        },
        {
            _id: new ObjectId(),
            id: "e87f90e1-1453-5c4d-9196-adddaf575760",
            name: "Elvish Mystic",
            manaCost: "{G}",
            cmc: 1,
            colorIdentity: ["G"],
            multiverseid: 512326,
            types: ["Creature"],
            imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=512326&type=card",
            rarity: "Special"
        },
        {
            _id: new ObjectId(),
            id: "e87f90e1-1453-5c4d-9196-adddaf575760",
            name: "Elvish Mystic",
            manaCost: "{G}",
            cmc: 1,
            colorIdentity: ["G"],
            multiverseid: 512326,
            types: ["Creature"],
            imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=512326&type=card",
            rarity: "Special"
        },
        {
            _id: new ObjectId(),
            id: "912101c7-cb9f-59df-8761-7eccdbb05c13",
            name: "Healer's Hawk",
            manaCost: "{W}",
            cmc: 1,
            colorIdentity: ["W"],
            multiverseid: 489591,
            types: ["Creature"],
            imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=489591&type=card",
            rarity: "Common"
        },
        {
            _id: new ObjectId(),
            id: "912101c7-cb9f-59df-8761-7eccdbb05c13",
            name: "Healer's Hawk",
            manaCost: "{W}",
            cmc: 1,
            colorIdentity: ["W"],
            multiverseid: 489591,
            types: ["Creature"],
            imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=489591&type=card",
            rarity: "Common"
        },
        {
            _id: new ObjectId(),
            id: "912101c7-cb9f-59df-8761-7eccdbb05c13",
            name: "Healer's Hawk",
            manaCost: "{W}",
            cmc: 1,
            colorIdentity: ["W"],
            multiverseid: 489591,
            types: ["Creature"],
            imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=489591&type=card",
            rarity: "Common"
        },
        {
            _id: new ObjectId(),
            id: "9c74e719-0d75-56a3-8afc-1c2d542fb99c",
            name: "Llanowar Elves",
            manaCost: "{G}",
            cmc: 1,
            colorIdentity: ["G"],
            multiverseid: 450261,
            types: ["Creature"],
            imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=450261&type=card",
            rarity: "Common"
        },
        {
            _id: new ObjectId(),
            id: "9c74e719-0d75-56a3-8afc-1c2d542fb99c",
            name: "Llanowar Elves",
            manaCost: "{G}",
            cmc: 1,
            colorIdentity: ["G"],
            multiverseid: 450261,
            types: ["Creature"],
            imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=450261&type=card",
            rarity: "Common"
        },
        {
            _id: new ObjectId(),
            id: "9c74e719-0d75-56a3-8afc-1c2d542fb99c",
            name: "Llanowar Elves",
            manaCost: "{G}",
            cmc: 1,
            colorIdentity: ["G"],
            multiverseid: 450261,
            types: ["Creature"],
            imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=450261&type=card",
            rarity: "Common"
        },
        {
            _id: new ObjectId(),
            id: "d451691b-6cc7-5ea7-968b-2abae1beb622",
            name: "Ajani's Pridemate",
            manaCost: "{1}{W}",
            cmc: 2,
            colorIdentity: ["W"],
            multiverseid: 460931,
            types: ["Creature"],
            imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460931&type=card",
            rarity: "Uncommon"
        },
        {
            _id: new ObjectId(),
            id: "d451691b-6cc7-5ea7-968b-2abae1beb622",
            name: "Ajani's Pridemate",
            manaCost: "{1}{W}",
            cmc: 2,
            colorIdentity: ["W"],
            multiverseid: 460931,
            types: ["Creature"],
            imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460931&type=card",
            rarity: "Uncommon"
        },
        {
            _id: new ObjectId(),
            id: "d451691b-6cc7-5ea7-968b-2abae1beb622",
            name: "Ajani's Pridemate",
            manaCost: "{1}{W}",
            cmc: 2,
            colorIdentity: ["W"],
            multiverseid: 460931,
            types: ["Creature"],
            imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460931&type=card",
            rarity: "Uncommon"
        },
        {
            _id: new ObjectId(),
            id: "72848888-20cb-5a1d-b34a-aead3c3c7159",
            name: "Pride of Conquerors",
            manaCost: "{1}{W}",
            cmc: 2,
            colorIdentity: ["W"],
            multiverseid: 439674,
            types: ["Instant"],
            imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=439674&type=card",
            rarity: "Uncommon"
        },
        {
            _id: new ObjectId(),
            id: "72848888-20cb-5a1d-b34a-aead3c3c7159",
            name: "Pride of Conquerors",
            manaCost: "{1}{W}",
            cmc: 2,
            colorIdentity: ["W"],
            multiverseid: 439674,
            types: ["Instant"],
            imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=439674&type=card",
            rarity: "Uncommon"
        },
        {
            _id: new ObjectId(),
            id: "72848888-20cb-5a1d-b34a-aead3c3c7159",
            name: "Pride of Conquerors",
            manaCost: "{1}{W}",
            cmc: 2,
            colorIdentity: ["W"],
            multiverseid: 439674,
            types: ["Instant"],
            imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=439674&type=card",
            rarity: "Uncommon"
        },
        {
            _id: new ObjectId(),
            id: "db6cf67d-344c-5205-9396-2edc74445efa",
            name: "Venerated Loxodon",
            manaCost: "{4}{W}",
            cmc: 5,
            colorIdentity: ["W"],
            multiverseid: 612463,
            types: ["Creature"],
            imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=612463&type=card",
            rarity: "Rare"
        },
        {
            _id: new ObjectId(),
            id: "db6cf67d-344c-5205-9396-2edc74445efa",
            name: "Venerated Loxodon",
            manaCost: "{4}{W}",
            cmc: 5,
            colorIdentity: ["W"],
            multiverseid: 612463,
            types: ["Creature"],
            imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=612463&type=card",
            rarity: "Rare"
        },
        {
            _id: new ObjectId(),
            id: "db6cf67d-344c-5205-9396-2edc74445efa",
            name: "Venerated Loxodon",
            manaCost: "{4}{W}",
            cmc: 5,
            colorIdentity: ["W"],
            multiverseid: 612463,
            types: ["Creature"],
            imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=612463&type=card",
            rarity: "Rare"
        },
        {
            _id: new ObjectId(),
            id: "41e731d9-eaf6-5c30-84df-2c30ebb15312",
            name: "Emmara, Soul of the Accord",
            manaCost: "{G}{W}",
            cmc: 2,
            colorIdentity: ["G", "W"],
            multiverseid: 452918,
            types: ["Creature"],
            imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=452918&type=card",
            rarity: "Rare"
        },
        {
            _id: new ObjectId(),
            id: "41e731d9-eaf6-5c30-84df-2c30ebb15312",
            name: "Emmara, Soul of the Accord",
            manaCost: "{G}{W}",
            cmc: 2,
            colorIdentity: ["G", "W"],
            multiverseid: 452918,
            types: ["Creature"],
            imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=452918&type=card",
            rarity: "Rare"
        },
        {
            _id: new ObjectId(),
            id: "41e731d9-eaf6-5c30-84df-2c30ebb15312",
            name: "Emmara, Soul of the Accord",
            manaCost: "{G}{W}",
            cmc: 2,
            colorIdentity: ["G", "W"],
            multiverseid: 452918,
            types: ["Creature"],
            imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=452918&type=card",
            rarity: "Rare"
        },
        {
            _id: new ObjectId(),
            id: "a56a316f-6d97-5185-9f24-260453e70ac3",
            name: "Pacifism",
            manaCost: "{1}{W}",
            cmc: 2,
            colorIdentity: ["W"],
            multiverseid: 5748,
            types: ["Enchantment"],
            imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=5748&type=card",
            rarity: "Common"
        },
        {
            _id: new ObjectId(),
            id: "a56a316f-6d97-5185-9f24-260453e70ac3",
            name: "Pacifism",
            manaCost: "{1}{W}",
            cmc: 2,
            colorIdentity: ["W"],
            multiverseid: 5748,
            types: ["Enchantment"],
            imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=5748&type=card",
            rarity: "Common"
        },
        {
            _id: new ObjectId(),
            id: "a56a316f-6d97-5185-9f24-260453e70ac3",
            name: "Pacifism",
            manaCost: "{1}{W}",
            cmc: 2,
            colorIdentity: ["W"],
            multiverseid: 5748,
            types: ["Enchantment"],
            imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=5748&type=card",
            rarity: "Common"
        },
        {
            _id: new ObjectId(),
            id: "a56a316f-6d97-5185-9f24-260453e70ac3",
            name: "Pacifism",
            manaCost: "{1}{W}",
            cmc: 2,
            colorIdentity: ["W"],
            multiverseid: 5748,
            types: ["Enchantment"],
            imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=5748&type=card",
            rarity: "Common"
        },
        {
            _id: new ObjectId(),
            id: "60bc023d-ce29-5050-bf25-cc4ff61f9f00",
            name: "Conclave Tribunal",
            manaCost: "{3}{W}",
            cmc: 4,
            colorIdentity: ["W"],
            multiverseid: 612426,
            types: ["Enchantment"],
            imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=612426&type=card",
            rarity: "Uncommon"
        },
        {
            _id: new ObjectId(),
            id: "60bc023d-ce29-5050-bf25-cc4ff61f9f00",
            name: "Conclave Tribunal",
            manaCost: "{3}{W}",
            cmc: 4,
            colorIdentity: ["W"],
            multiverseid: 612426,
            types: ["Enchantment"],
            imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=612426&type=card",
            rarity: "Uncommon"
        },
        {
            _id: new ObjectId(),
            id: "60bc023d-ce29-5050-bf25-cc4ff61f9f00",
            name: "Conclave Tribunal",
            manaCost: "{3}{W}",
            cmc: 4,
            colorIdentity: ["W"],
            multiverseid: 612426,
            types: ["Enchantment"],
            imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=612426&type=card",
            rarity: "Uncommon"
        },
        {
            _id: new ObjectId(),
            id: "60bc023d-ce29-5050-bf25-cc4ff61f9f00",
            name: "Conclave Tribunal",
            manaCost: "{3}{W}",
            cmc: 4,
            colorIdentity: ["W"],
            multiverseid: 612426,
            types: ["Enchantment"],
            imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=612426&type=card",
            rarity: "Uncommon"
        },
        {
            _id: new ObjectId(),
            id: "a85906bb-9288-50fb-93d3-cc719240e0d3",
            name: "Blessing of Belzenlok",
            manaCost: "{B}",
            cmc: 1,
            colorIdentity: ["B"],
            multiverseid: 442965,
            types: ["Instant"],
            imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442965&type=card",
            rarity: "Common"
        },
        {
            _id: new ObjectId(),
            id: "a85906bb-9288-50fb-93d3-cc719240e0d3",
            name: "Blessing of Belzenlok",
            manaCost: "{B}",
            cmc: 1,
            colorIdentity: ["B"],
            multiverseid: 442965,
            types: ["Instant"],
            imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442965&type=card",
            rarity: "Common"
        },
        {
            _id: new ObjectId(),
            id: "a85906bb-9288-50fb-93d3-cc719240e0d3",
            name: "Blessing of Belzenlok",
            manaCost: "{B}",
            cmc: 1,
            colorIdentity: ["B"],
            multiverseid: 442965,
            types: ["Instant"],
            imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442965&type=card",
            rarity: "Common"
        },
        {
            _id: new ObjectId(),
            id: "a85906bb-9288-50fb-93d3-cc719240e0d3",
            name: "Blessing of Belzenlok",
            manaCost: "{B}",
            cmc: 1,
            colorIdentity: ["B"],
            multiverseid: 442965,
            types: ["Instant"],
            imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442965&type=card",
            rarity: "Common"
        },
        {
            _id: new ObjectId(),
            id: "4f651d96-55d5-5cbc-9bb8-863c8c58d8ad",
            name: "Adanto Vanguard",
            manaCost: "{1}{W}",
            cmc: 2,
            colorIdentity: ["W"],
            multiverseid: 435152,
            types: ["Creature"],
            imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=435152&type=card",
            rarity: "Uncommon"
        },
        {
            _id: new ObjectId(),
            id: "4f651d96-55d5-5cbc-9bb8-863c8c58d8ad",
            name: "Adanto Vanguard",
            manaCost: "{1}{W}",
            cmc: 2,
            colorIdentity: ["W"],
            multiverseid: 435152,
            types: ["Creature"],
            imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=435152&type=card",
            rarity: "Uncommon"
        }
    ],
    deckImageUrl: "http://localhost:4000/assets/images/decks/1.webp",
    favorited: false
};
